import assert from 'node:assert/strict';
import { OrchestratorAgent } from '../agents/orchestrator.js';
import { manifestFixture } from './manifestFixture.js';
import { createExperimentAssignment } from '../core/experimentProtocol.js';
import type { VectorStoreService } from '../services/vectorStore.js';
let recalls = 0, writes = 0, searches = 0;
const store = { async recallMemories() { recalls++; return [{ content: 'CONTAMINATED memory', score: 1 }]; }, async saveMemory() { writes++; return true; }, async hybridSearch() { searches++; return []; } } as unknown as VectorStoreService;
const experiment = createExperimentAssignment({ seed: 71, durationMonths: 2, scenarioContext: 'fixed' }, { experimentId: 'paired-test', replicaId: '1', interventionId: 'scrum' });
const config = { ...manifestFixture.config, experiment, parametros_simulacao: { ...manifestFixture.config.parametros_simulacao, seed: experiment.scenarioSeed } };
const run = await new OrchestratorAgent(undefined, store, manifestFixture.dependencies).runSimulation(['first', 'second'], manifestFixture.personas, config);
assert.equal(recalls, 0, 'experimental conditions must not recall shared mutable memories');
assert.equal(writes, 0, 'experimental conditions must not write memory into later arms');
assert.equal(searches, 0, 'experimental RAG must use frozen config/profile inputs, not shared mutable retrieval');
assert.ok(!run.state.scratchpad.includes('CONTAMINATED'));
assert.deepEqual(run.state.manifest?.protocol?.exogenousSchedule, experiment.exogenousSchedule);
const shocks = run.state.personaTraces?.flatMap(trace => trace.events.filter(event => event.kind === 'exogenous')) ?? [];
assert.equal(shocks.length, 4, 'each person/turn records the shared environmental shock');
const reverse = await new OrchestratorAgent(undefined, store, manifestFixture.dependencies).runSimulation(['first', 'second'], manifestFixture.personas, { ...config, experiment: { ...experiment, interventionId: 'kanban', conditionId: 'kanban' } });
assert.deepEqual(shocks.map(event => event.text), reverse.state.personaTraces?.flatMap(trace => trace.events.filter(event => event.kind === 'exogenous')).map(event => event.text));
assert.deepEqual(run.state.personaTraces?.map(trace => trace.before).slice(0, 2), reverse.state.personaTraces?.map(trace => trace.before).slice(0, 2), 'initial people must be identical across arms');
console.log('  ✓ experimental execution isolates memory/retrieval and records identical exogenous shocks');
const withIncident = { ...experiment, exogenousSchedule: experiment.exogenousSchedule.map(shock => ({ ...shock, incidentUniform: 0 })) };
const incidentRun = await new OrchestratorAgent(undefined, store, manifestFixture.dependencies).runSimulation(['first', 'second'], manifestFixture.personas, { ...config, experiment: withIncident });
const incidentTraces = incidentRun.state.personaTraces!;
assert.equal(incidentTraces.filter(trace => trace.events.some(event => event.type === 'environment-incident')).length, 4, 'incident schedule reaches every persona/turn');
assert.ok(incidentTraces.every(trace => { const block = JSON.parse(trace.events.find(event => event.type === 'sampled-work-block')!.text); return block.usableExecutionHours + block.reservedReviewHours <= 1.5; }), 'incident downtime consumes sampled capacity');
assert.ok(incidentTraces.slice(0, 2).some((trace, index) => trace.after.estresse !== run.state.personaTraces![index].after.estresse), 'incident pressure reaches the brain transition');
