import assert from 'node:assert/strict';
import { deriveInitialBrain } from '../core/employeeBrainCore.js';
import { TraceRecorder } from '../services/TraceRecorder.js';
import { evaluateIndividualMetrics } from '../services/IndividualMetrics.js';
const work = await import('../core/syntheticWork.js').catch(() => null);
assert.ok(work, 'normal simulation requires explicit attributed synthetic tasks');
const people = ['a', 'b'].map(id => deriveInitialBrain({ id, nome: 'Same', cargo: 'Engineer' }, 71));
const traces = () => { const recorder = new TraceRecorder(); recorder.recordTurn('run', 1, people, people, []); return recorder.snapshot(); };
const first = work.simulateWorkBlock(traces(), { seed: 71 });
assert.ok(first.every(trace => trace.tasks.length > 0));
assert.ok(first.flatMap(trace => trace.tasks).every(task => task.source === 'synthetic' && task.evidenceIds.every(id => first.flatMap(trace => trace.events).some(event => event.eventId === id))));
assert.deepEqual(first, work.simulateWorkBlock(traces(), { seed: 71 }));
const stressed = traces().map(trace => ({ ...trace, before: { ...trace.before, estresse: 100, energia: 1 }, after: { ...trace.after, estresse: 100, energia: 1 } }));
assert.deepEqual(first.map(trace => trace.tasks), work.simulateWorkBlock(stressed, { seed: 71 }).map(trace => trace.tasks), 'stress cannot manufacture a performance penalty');
assert.ok(evaluateIndividualMetrics(first).every(person => person.metrics.find(metric => metric.id === 'delivery')?.value !== null));
const unavailable = traces().map(trace => ({ ...trace, before: { ...trace.before, status: 'licenca' as const }, after: { ...trace.after, status: 'licenca' as const } }));
assert.ok(work.simulateWorkBlock(unavailable, { seed: 71 }).every(trace => trace.tasks.length === 0));
const incident = work.incidentContext({ incidentUniform: 0.01 });
assert.equal(incident.occurred, true);
assert.equal(incident.pressureDelta, 0.1);
assert.equal(incident.downtimeHours, 0.5);
assert.equal(work.incidentContext({ incidentUniform: 0.99 }).occurred, false);
const interrupted = work.simulateWorkBlock(traces(), { seed: 71, shock: { turnId: 1, pressureDelta: 0, demandMultiplier: 1, incidentUniform: 0.01, source: 'synthetic' } });
assert.ok(interrupted.every(trace => trace.events.some(event => event.type === 'environment-incident')));
assert.equal(first[0].tasks.map(task => task.opportunityUnits).reduce((a,b)=>a+b,0), interrupted[0].tasks.map(task => task.opportunityUnits).reduce((a,b)=>a+b,0), 'incident changes capacity, not assigned demand');
assert.throws(() => work.resolveWorkPolicy({ reviewProbability: 2 }), /policy/i);
const capped = work.simulateWorkBlock(traces(), { seed: 71, policy: { capacityHours: 1, reviewHours: 0.75, reviewProbability: 1 } });
assert.ok(capped.every(trace => JSON.parse(trace.events.find(event => event.type === 'sampled-work-block')!.text).reservedReviewHours <= 1), 'review reservations cannot exceed sampled capacity');
const corrected = work.simulateWorkBlock(traces(), { seed: 71, policy: { capacityHours: 12, defectProbability: 1, reviewProbability: 1, detectionProbability: 1 } });
assert.ok(corrected.every(trace => trace.tasks.every(task => task.status === 'accepted' && task.reworkUnits === 1 && !task.censored)));
assert.ok(corrected.every(trace => trace.events.some(event => event.kind === 'collaboration' && event.relatedPersonaIds?.length === 1)));
const rejected = work.simulateWorkBlock(traces(), { seed: 71, policy: { capacityHours: 12, defectProbability: 1, reviewProbability: 0 } });
assert.ok(rejected.every(trace => trace.tasks.every(task => task.status === 'rejected' && task.censored && task.leadTimeHours === undefined)));
assert.ok(rejected.every(trace => !trace.events.some(event => event.kind === 'collaboration')));
console.log('  ✓ attributed work blocks, independent personality, replay, availability and exogenous incidents');
