import React, { useMemo } from 'react';
import { ScatterChart, Scatter, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, Legend, ReferenceLine } from 'recharts';
import type { BatchResult } from '../services/batchService';
import { buildReportData, type ReportData } from '../services/reportData';
const number = (value: number | null) => value === null ? 'Indisponível' : value.toLocaleString('pt-BR', { maximumFractionDigits: 8 });
export const BatchResultsChart: React.FC<{ result: BatchResult; report?: ReportData }> = ({ result, report: supplied }) => {
    const fallback: ReportData = useMemo(() => supplied ?? buildReportData({ mode: 'batch', outputs: result.outputs, batch: result }), [result, supplied]);
    const metrics = fallback.metrics;
    const value = (runId: string, id: string) => metrics.find(row => row.runId === runId && row.group === 'run' && row.id === id)?.value ?? null;
    const scatter = fallback.runs.filter(run => run.status === 'completed' && value(run.id, 'totalRoi') !== null && value(run.id, 'finalAdoption') !== null).map(run => ({ id: run.id, roi: value(run.id, 'totalRoi'), adoption: value(run.id, 'finalAdoption') }));
    return <div className="space-y-6 w-full">
        <section className="border border-zinc-500/40 rounded p-5 space-y-4" aria-label="Métricas do lote"><h3 className="text-lg font-semibold">Medidas das réplicas independentes</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-zinc-500/40"><th scope="col" className="py-3 pr-4">Medida</th><th scope="col" className="pr-4">Média</th><th scope="col" className="pr-4">Unidade</th><th scope="col" className="pr-4">IC 95%</th><th scope="col" className="pr-4">n independente</th><th scope="col">Excluídos</th></tr></thead><tbody>{metrics.filter(row => row.group === 'aggregate').map(row => <tr key={row.key} className="border-b border-zinc-500/20"><th scope="row" className="py-3 pr-4 font-medium">{row.label}</th><td className="pr-4 font-mono tabular-nums">{number(row.value)}</td><td className="pr-4">{row.unit}</td><td className="pr-4 font-mono">{row.interval95 ? row.interval95.map(number).join(' a ') : 'Indisponível'}</td><td className="pr-4 font-mono">{row.nIndependent}</td><td className="font-mono">{row.nExcluded}</td></tr>)}</tbody></table></div><p className="text-xs">Dispersão descreve estes cenários sintéticos. A capacidade de prever resultados observados permanece sem validação. Falhas, fixtures e execuções degradadas ficam fora das médias.</p></section>
        <section className="border border-zinc-500/40 rounded p-5 space-y-4"><h3 className="text-lg font-semibold">ROI projetado × adoção simulada</h3>{scatter.length ? <div className="h-64 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 700, height: 256 }}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke="#52525b" /><XAxis type="number" dataKey="adoption" name="Adoção" unit="%" /><YAxis type="number" dataKey="roi" name="ROI" unit="%" /><Tooltip cursor={{ strokeDasharray: '3 3' }} /><ReferenceLine y={0} stroke="#71717a" /><Scatter name="Execuções disponíveis" data={scatter} fill="#047857" /></ScatterChart></ResponsiveContainer></div> : <p className="text-sm">Indisponível: o gráfico exige ROI e adoção na mesma execução.</p>}</section>
        {(['month', 'turn'] as const).map(timeUnit => {
            const timeline = metrics.filter(row => row.group === 'aggregate-timeline' && row.timeUnit === timeUnit);
            if (!timeline.length) return null;
            const points = [...new Set(timeline.map(row => row.turnId!))].sort((a, b) => a - b).map(turn => ({ turn, roi: timeline.find(row => row.id === 'roi' && row.turnId === turn)?.value ?? null, adoption: timeline.find(row => row.id === 'adoptionRate' && row.turnId === turn)?.value ?? null }));
            return <section key={timeUnit} className="border border-zinc-500/40 rounded p-5 space-y-4"><h3 className="text-lg font-semibold">Evolução média por {timeUnit === 'turn' ? 'turno' : 'mês'}</h3>{points.some(point => point.roi !== null || point.adoption !== null) ? <div className="h-72 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 700, height: 288 }}><LineChart data={points}><CartesianGrid strokeDasharray="3 3" stroke="#52525b" /><XAxis dataKey="turn" /><YAxis unit="%" /><Tooltip /><Legend /><ReferenceLine y={0} stroke="#71717a" /><Line dataKey="roi" name="ROI projetado (%)" stroke="#b45309" connectNulls={false} /><Line dataKey="adoption" name="Adoção simulada (%)" stroke="#047857" connectNulls={false} /></LineChart></ResponsiveContainer></div> : <p className="text-sm">Indisponível: nenhuma trajetória tem estas dimensões medidas.</p>}<p className="text-xs">Médias por ponto usam apenas réplicas elegíveis com a dimensão disponível. Lacunas e valores negativos são preservados.</p></section>;
        })}
        <details className="text-sm"><summary className="cursor-pointer focus-visible:outline">Todas as tentativas do lote</summary><ul className="list-disc pl-5 mt-3 space-y-2">{fallback.runs.map(run => <li key={run.id}>Réplica {run.replicaId}: {run.status} · ROI {number(value(run.id, 'totalRoi'))}% · adoção {number(value(run.id, 'finalAdoption'))}%</li>)}</ul></details>
    </div>;
};
