import React, { useMemo, useState } from 'react';
import { BarChart, Bar, Cell, ErrorBar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from 'recharts';
import { Download, Moon, Sun } from 'lucide-react';
import type { SimulationOutput, SimulationConfig } from '../types';
import { compareConditions, COMPARISON_METRICS, type ComparisonMetric } from '../services/experimentResults';
import { BrutalButton } from './ui/BrutalButton';
import { IndividualEvaluationPanel } from './IndividualEvaluationPanel';
import type { FailedCondition } from '../services/interactiveRuns';
import { buildReportData } from '../services/reportData';
import { ArticleExportControls } from './ArticleExportControls';

interface ComparisonDashboardProps { results: SimulationOutput[]; config: SimulationConfig; onReset: () => void; failures?: FailedCondition[] }
const number = (value: number | null) => value === null ? 'Indisponível' : value.toLocaleString('pt-BR', { maximumFractionDigits: 5 });
const interval = (bounds: [number, number] | null) => bounds ? `${number(bounds[0])} a ${number(bounds[1])}` : 'Indisponível';

export const ComparisonDashboard: React.FC<ComparisonDashboardProps> = ({ results, config, onReset, failures = [] }) => {
    const [darkMode, setDarkMode] = useState(true);
    const [metric, setMetric] = useState<ComparisonMetric>('totalRoi');
    const [selectedRun, setSelectedRun] = useState(0);
    const articleReport = useMemo(() => buildReportData({ mode: 'comparison', outputs: results, config, failures }), [results, config, failures]);
    const report = articleReport.comparisons[metric]!;
    const surface = darkMode ? 'bg-[#18181b] border-zinc-700 text-zinc-100' : 'bg-white border-zinc-300 text-zinc-900';
    const bg = darkMode ? 'bg-[#09090b] text-zinc-100' : 'bg-zinc-100 text-zinc-900';
    const chartData = report.conditions.filter(condition => condition.statistics.mean !== null).map(condition => ({ id: condition.id, label: `${condition.label} · ${condition.id}`, mean: condition.statistics.mean,
        error: condition.statistics.interval95 ? [condition.statistics.mean! - condition.statistics.interval95[0], condition.statistics.interval95[1] - condition.statistics.mean!] : undefined }));
    const labelFor = (id: string) => `${report.conditions.find(condition => condition.id === id)?.label ?? id} · ${id}`;
    const download = () => {
        const url = URL.createObjectURL(new Blob([JSON.stringify({ config, results, failures, comparison: report }, null, 2)], { type: 'application/json' }));
        const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'framesim-comparison.json'; anchor.click(); URL.revokeObjectURL(url);
    };
    return <div className={`fixed inset-0 z-50 overflow-y-auto ${bg}`}><main className="max-w-[1400px] mx-auto p-5 md:p-10 space-y-8">
        <nav className="flex flex-wrap items-center justify-between gap-4 border-b border-zinc-500/30 pb-5"><h1 className="text-2xl md:text-3xl font-bold">FrameSIM · Comparação</h1><div className="flex flex-wrap items-center gap-3"><button type="button" className="p-3 rounded border border-zinc-500/40 focus-visible:outline" onClick={() => setDarkMode(!darkMode)} aria-label={darkMode ? 'Ativar tema claro' : 'Ativar tema escuro'}>{darkMode ? <Sun size={18} /> : <Moon size={18} />}</button><BrutalButton variant="secondary" onClick={onReset}>Nova comparação</BrutalButton><BrutalButton onClick={download}><Download size={16} className="mr-2" />Dados JSON</BrutalButton></div></nav>
        <ArticleExportControls report={articleReport} /><header className="space-y-3 max-w-3xl"><h2 className="text-2xl font-bold">Desempenho por condição</h2><p className="text-sm leading-relaxed">Compare cada dimensão na sua unidade. O delta usa a primeira condição como referência e só aceita pares com mesma equipe, cenário, choques e revisão do código. Uma réplica permite descrever o resultado; não permite estimar um intervalo.</p><p className="text-sm font-medium">Validação empírica pendente · resultados sintéticos dos cenários testados.</p></header>
        <section className={`border rounded p-5 md:p-6 space-y-5 ${surface}`} aria-label="Medidas comparativas">
            <div className="flex flex-wrap items-center justify-between gap-4"><h3 className="text-lg font-semibold">Medida da equipe</h3><label className="flex flex-wrap items-center gap-3 text-sm" htmlFor="comparison-metric">Dimensão<select id="comparison-metric" value={metric} onChange={event => setMetric(event.target.value as ComparisonMetric)} className={`min-h-11 border rounded px-3 py-2 focus-visible:outline ${surface}`}>{Object.entries(COMPARISON_METRICS).map(([key, definition]) => <option key={key} value={key}>{definition.label} ({definition.unit})</option>)}</select></label></div>
            <div className="overflow-x-auto"><table className="w-full text-left text-sm border-collapse"><thead><tr className="border-b border-zinc-500/40"><th scope="col" className="py-3 pr-4">Condição</th><th scope="col" className="pr-4">Média ({report.unit})</th><th scope="col" className="pr-4">IC 95%</th><th scope="col" className="pr-4">n independente</th><th scope="col">Excluídos</th></tr></thead><tbody>{report.conditions.map(condition => <tr key={condition.id} className="border-b border-zinc-500/20"><th scope="row" className="py-3 pr-4 font-medium">{condition.label}<span className="block font-mono text-xs mt-1 break-all">{condition.id}</span></th><td className="pr-4 font-mono tabular-nums">{number(condition.statistics.mean)}</td><td className="pr-4 font-mono tabular-nums">{interval(condition.statistics.interval95)}</td><td className="pr-4 font-mono">{condition.statistics.nIndependent}</td><td className="font-mono">{condition.statistics.nExcluded}</td></tr>)}</tbody></table></div>
            {chartData.length ? <div className="h-72 min-w-0 w-full"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 700, height: 288 }}><BarChart data={chartData} margin={{ top: 15, right: 20, left: 12, bottom: 25 }}><CartesianGrid strokeDasharray="3 3" stroke={darkMode ? '#3f3f46' : '#d4d4d8'} vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 11, fill: darkMode ? '#d4d4d8' : '#3f3f46' }} /><YAxis tick={{ fontSize: 11, fill: darkMode ? '#d4d4d8' : '#3f3f46' }} label={{ value: report.unit, angle: -90, position: 'insideLeft' }} /><ReferenceLine y={0} stroke="#71717a" /><Tooltip contentStyle={{ backgroundColor: darkMode ? '#18181b' : '#fff', border: '1px solid #71717a', color: darkMode ? '#fff' : '#18181b' }} /><Bar dataKey="mean" name={COMPARISON_METRICS[metric].label}>{chartData.map(point => <Cell key={point.id} fill={point.mean! < 0 ? '#b45309' : '#047857'} />)}<ErrorBar dataKey="error" width={8} stroke={darkMode ? '#e4e4e7' : '#27272a'} /></Bar></BarChart></ResponsiveContainer></div> : <p className="text-sm">Não há medidas disponíveis nesta dimensão.</p>}
            <p className="text-xs">Intervalo t sobre execuções independentes quando n ≥ 2. Dados ausentes, fixtures e condições degradadas ficam fora da inferência; perdas são preservadas.</p>
        </section>
        <section className={`border rounded p-5 md:p-6 space-y-4 ${surface}`} aria-label="Delta pareado"><h3 className="text-lg font-semibold">Delta pareado · B − A</h3><p className="text-sm max-w-prose">Bootstrap reamostra pares completos no nível da execução. Para dimensões em %, o delta está em pontos percentuais. Nenhuma soma entre escalas escolhe uma condição vencedora.</p>
            <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-zinc-500/40"><th scope="col" className="py-3 pr-4">A → B</th><th scope="col" className="pr-4">Delta</th><th scope="col" className="pr-4">IC 95%</th><th scope="col" className="pr-4">n independente</th><th scope="col">Pares excluídos</th></tr></thead><tbody>{report.comparisons.map(pair => <tr key={pair.b} className="border-b border-zinc-500/20"><th scope="row" className="py-3 pr-4 font-medium">{labelFor(pair.a)} → {labelFor(pair.b)}</th><td className="pr-4 font-mono">{number(pair.statistics.delta)}</td><td className="pr-4 font-mono">{interval(pair.statistics.interval95)}</td><td className="pr-4 font-mono">{pair.statistics.nIndependent}</td><td className="font-mono">{pair.statistics.nExcluded}</td></tr>)}</tbody></table></div>
            {report.comparisons.some(pair => pair.excludedReplicas.length) && <details className="text-sm"><summary className="cursor-pointer focus-visible:outline">Por que alguns pares foram excluídos</summary><ul className="list-disc pl-5 space-y-2 mt-3">{report.comparisons.flatMap(pair => pair.excludedReplicas.map(excluded => <li key={`${pair.b}-${excluded.replicaId}`}>{labelFor(pair.b)} · {excluded.replicaId}: {excluded.reason}</li>))}</ul></details>}
        </section>
        {!!results.length && <><label htmlFor="comparison-run" className="block text-sm font-medium">Execução para inspecionar pessoas<select id="comparison-run" value={Math.min(selectedRun, results.length - 1)} onChange={event => setSelectedRun(Number(event.target.value))} className={`block w-full mt-2 min-h-11 rounded border px-3 py-2 focus-visible:outline ${surface}`}>{results.map((output, index) => <option key={output.manifest?.runId ?? index} value={index}>{output.frameworkName} · {output.manifest?.protocol?.conditionId ?? index + 1} · réplica {output.manifest?.replicaId ?? 'não registrada'}</option>)}</select></label><IndividualEvaluationPanel data={results[Math.min(selectedRun, results.length - 1)]} darkMode={darkMode} /></>}
        <details className="text-sm border-t border-zinc-500/30 pt-4"><summary className="cursor-pointer focus-visible:outline">Método e limitações</summary><ul className="list-disc pl-5 space-y-2 mt-3">{report.limitations.map(item => <li key={item}>{item}</li>)}</ul></details>
    </main></div>;
};
