import assert from 'node:assert/strict';
import * as batch from '../services/batchService';
import { MOCK_SIMULATION_RESULT } from '../services/mockData';
import type { SimulationOutput } from '../types';
const summarize = (batch as unknown as { summarizeOutputs?: (outputs: SimulationOutput[]) => import('../types').BatchSummary }).summarizeOutputs;
assert.ok(summarize, 'batch summary must expose the verified statistical contract');
const one = summarize([{ ...MOCK_SIMULATION_RESULT, summary: { ...MOCK_SIMULATION_RESULT.summary, totalRoi: -12 } }]);
assert.equal(one.averageRoi, -12);
assert.equal(one.confidenceInterval95, null);
assert.equal(one.stdDevRoi, null);
assert.equal(one.nIndependent, 1);
const fixture = summarize([{ ...MOCK_SIMULATION_RESULT, execution: { mode: 'fixture', provider: 'none', model: 'fixture', attempts: 0 } }]);
assert.equal(fixture.averageRoi, null);
assert.equal(fixture.nIndependent, 0);
assert.equal(fixture.nExcluded, 1);
const missing = summarize([{ ...MOCK_SIMULATION_RESULT, summary: { ...MOCK_SIMULATION_RESULT.summary, finalAdoption: null, totalRoi: -12 } }]);
assert.equal(missing.averageRoi, -12);
assert.equal(missing.averageAdoption, null);
console.log('  ✓ batch n=1 interval, excluded fixtures, losses and missing adoption');
