import assert from 'node:assert/strict';
const statistics = await import('../services/comparisonStatistics').catch(() => null);
assert.ok(statistics, 'comparison statistics must be implemented');
const one = statistics.summarizeIndependent([{ replicaId: '1', value: -12 }]);
assert.equal(one.mean, -12);
assert.equal(one.interval95, null, 'a single independent replica cannot estimate an interval');
assert.equal(one.sampleSD, null);
const sample = statistics.summarizeIndependent([{ replicaId: '1', value: -10 }, { replicaId: '2', value: -20 }, { replicaId: '3', value: 0 }]);
assert.equal(sample.mean, -10);
assert.equal(sample.sampleSD, 10, 'sample variance uses n-1');
assert.ok(sample.interval95![0] < -30 && sample.interval95![1] > 10, 'small samples need t critical values');
const pairs = [{ replicaId: '1', a: -10, b: -5 }, { replicaId: '2', a: 100, b: 105 }, { replicaId: '3', a: -200, b: -195 }];
const paired = statistics.pairedComparison(pairs, { seed: 7, resamples: 1000 });
assert.equal(paired.delta, 5);
assert.equal(paired.nIndependent, 3);
assert.deepEqual(paired.interval95, [5, 5], 'bootstrap resamples complete pairs, never independent arms');
assert.deepEqual(paired, statistics.pairedComparison(pairs, { seed: 7, resamples: 1000 }));
assert.equal(statistics.pairedComparison([pairs[0]]).interval95, null);
assert.throws(() => statistics.pairedComparison([pairs[0], pairs[0]]), /Duplicate replica/);
const incomplete = statistics.pairedComparison([...pairs, { replicaId: '4', a: null, b: -10 }]);
assert.equal(incomplete.nIndependent, 3);
assert.equal(incomplete.nExcluded, 1);
assert.equal(statistics.summarizeIndependent([{ replicaId: 'fixture', value: 1000, status: 'fixture' }]).mean, null);
console.log('  ✓ independent units, sample variance, unavailable n=1 intervals, losses and complete-pair bootstrap');
