import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { IndividualEvaluationPanel } from '../components/IndividualEvaluationPanel';
import { evaluateIndividualMetrics } from '../RAG/src/services/IndividualMetrics';
import { deriveInitialBrain } from '../RAG/src/core/employeeBrainCore';
import type { SimulationOutput } from '../types';
const before = deriveInitialBrain({ id: 'a', nome: 'Same <script>', cargo: 'Engineer' }, 1);
const personaTraces = ['a', 'b'].map(id => ({ runId: 'run', personaId: id, turnId: 1, role: 'Engineer', before: { ...before, personaId: id }, after: { ...before, personaId: id }, events: [{ eventId: `evt-${id}`, personaId: id, turnId: 1, type: 'transition', text: 'Synthetic transition', kind: 'state-transition' as const, source: 'synthetic' as const }], tasks: [], source: 'synthetic' as const }));
const data = { keyPersonas: personaTraces.map(trace => ({ id: trace.personaId, name: before.nome, role: 'Engineer' })), personaTraces, individualEvaluations: evaluateIndividualMetrics(personaTraces) } as SimulationOutput;
const markup = renderToStaticMarkup(<IndividualEvaluationPanel data={data} />);
assert.ok(markup.includes('value="a"') && markup.includes('value="b"'), 'homonymous people must be separately selectable by ID');
assert.ok(markup.includes('Same &lt;script&gt;'));
assert.ok(markup.includes('Indisponível'), 'missing delivery is shown as missing');
assert.ok(markup.includes('Contexto simulado'));
assert.ok(markup.includes('evt-a'), 'evidence identity is inspectable');
assert.ok(markup.includes('Validação empírica pendente'));
data.individualEvaluations![0].leadTimeByClass = [{ classId: 'small-task', unit: 'hours', median: 1.25, nAccepted: 1, nCensored: 1, nMissingTiming: 0, observations: [{ taskId: 'done', hours: 1.25, censored: false, evidenceIds: ['evt-a'] }] }];
const flowMarkup = renderToStaticMarkup(<IndividualEvaluationPanel data={data} />);
assert.ok(flowMarkup.includes('small-task') && flowMarkup.includes('censurada'), 'flow distributions and censoring are inspectable in the panel');
console.log('  ✓ individual UI preserves identity, missing values, source and evidence');
