import assert from 'node:assert/strict';
import { MOCK_SIMULATION_RESULT } from '../services/mockData';
import { summarizeOutputs } from '../services/batchService';
const service = await import('../services/reportData').catch(() => null);
assert.ok(service, 'one report contract must feed UI and export');
const output = { ...MOCK_SIMULATION_RESULT, frameworkName: 'A & B', summary: { ...MOCK_SIMULATION_RESULT.summary, totalRoi: -12.345678901, finalAdoption: null }, timeline: [{ month: 1, roi: -0.123456789, adoptionRate: null, compliance: null, efficiency: 80 }] };
const report = service.buildReportData({ mode: 'individual', outputs: [output] });
assert.equal(report.metrics.find(row => row.id === 'totalRoi' && row.group === 'run')?.value, -12.345678901);
assert.equal(report.metrics.find(row => row.id === 'finalAdoption' && row.group === 'run')?.value, null);
assert.equal(service.reportTimeline(report, 0)[0].roi, -0.123456789);
assert.equal(service.reportTimeline(report, 0)[0].adoptionRate, null);
const records = [{ replicaId: '1', conditionId: 'a', seed: 1, status: 'completed' as const, output }, { replicaId: '2', conditionId: 'a', seed: 2, status: 'failed' as const }];
const batch = service.buildReportData({ mode: 'batch', outputs: [output], batch: { config: {} as any, outputs: [output], runs: records, summary: summarizeOutputs([output], records) } });
const roi = batch.metrics.find(row => row.id === 'totalRoi' && row.group === 'aggregate');
assert.equal(roi?.value, -12.345678901);
assert.equal(roi?.nIndependent, 1);
assert.equal(roi?.nExcluded, 1);
assert.equal(roi?.interval95, null);
assert.equal(batch.runs.length, 2);
assert.ok(batch.limitations.some(item => /observed|empirical/i.test(item)));
assert.ok(!JSON.stringify(service.buildReportData({ mode: 'individual', outputs: [{ ...output, apiKey: 'private' } as any], config: { apiKey: 'private' } as any })).includes('private'));
const complete = { ...output, resourceAllocation: [{ category: 'A & B', amount: 12.3456789 }, { category: 'A & B', amount: 2 }], sentimentBreakdown: [{ group: 'Same', value: 3 }], departmentReadiness: [{ department: 'Tech', score: 73.123 }], companyEvolution: { initialTeamSize: 10, finalTeamSize: 11, newHires: 2, turnover: 10, promotions: 1, capacityGrowth: 5, breakEvenProjection: 0, maturityLevelBefore: 2, maturityLevelAfter: 3, culturalShift: 'NEUTRO' as const } };
const visuals = service.buildReportData({ mode: 'individual', outputs: [complete], config: { workloadPolicy: { capacityHours: 3 } } as any });
assert.equal(visuals.metrics.find(row => row.id === 'resourceAllocation' && row.label === 'A & B')?.value, 12.3456789);
assert.equal(visuals.metrics.find(row => row.id === 'company.finalTeamSize')?.unit, 'pessoas');
assert.equal(visuals.metrics.filter(row => row.id === 'resourceAllocation').length, 2, 'duplicate labels cannot collapse identity');
assert.deepEqual(service.reportVisuals(visuals, 0).resourceAllocation, complete.resourceAllocation);
assert.deepEqual(visuals.config?.workloadPolicy, { capacityHours: 3 });
const failedAgentic = service.buildReportData({ mode: 'comparison', outputs: [], config: { simulationMode: 'agentic' } as any, failures: [{ label: 'A', experiment: { conditionId: 'a', replicaId: '1', exogenousSchedule: [] } as any, errorCode: 'Error' }] });
assert.ok(failedAgentic.runs[0].protocol, 'failed arms must retain their full protocol');
const turnBatch = service.buildReportData({ mode: 'batch', outputs: [{ ...output, timeUnit: 'turn' }] });
assert.ok(turnBatch.metrics.filter(row => row.id === 'efficiency').every(row => row.unit === '% da velocidade de referência'), 'aggregate and trajectory must preserve the same measured unit');
console.log('  ✓ report preserves integral values, nulls, failures and safe provenance');
