import assert from 'node:assert/strict';
import type { SingleSimulationConfig } from '../types';
const measurements = await import('../services/standardMeasurements').catch(() => null);
assert.ok(measurements, 'missing model data must not fabricate numeric trajectories');
const config = { frameworkName: 'Scrum', durationMonths: 2, companySize: 20, budgetLevel: 'medium', techDebtLevel: 'low', operationalVelocity: 'agile', seed: 71 } as SingleSimulationConfig;
const missing = measurements.normalizeStandardMeasurements({}, config, 71);
assert.equal(missing.summary.totalRoi, null);
assert.equal(missing.summary.finalAdoption, null);
assert.equal(missing.timeline.length, 2);
assert.ok(missing.timeline.every(point => point.roi === null && point.adoptionRate === null && point.rawData === undefined));
const raw = { featuresDelivered: 2, bugsGenerated: 1, criticalIncidents: 0, teamSize: 20, learningCurveFactor: 0.8 };
const complete = measurements.normalizeStandardMeasurements({ summary: { finalAdoption: 80, maturityScore: 7, monthsToComplete: 2, scenarioValidity: 90 }, timeline: [{ month: 1, adoptionRate: 40, rawData: raw }, { month: 2, adoptionRate: 80, rawData: raw }] }, config, 71);
assert.equal(typeof complete.summary.totalRoi, 'number');
assert.ok(complete.timeline.every(point => typeof point.roi === 'number'));
const censored = measurements.normalizeStandardMeasurements({ timeline: [{ month: 2, rawData: raw }] }, config, 71);
assert.equal(censored.summary.totalRoi, null);
assert.equal(censored.timeline[1].roi, null, 'cumulative ROI cannot bridge an unmeasured month');
assert.throws(() => measurements.normalizeStandardMeasurements({ timeline: [{ month: 1 }, { month: 1 }] }, config, 71), /duplicate/i);
console.log('  ✓ standard measurements preserve unavailable data and cumulative gaps');
